# Generated by Django 5.2.7 on 2025-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_article_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Default status for new articles created via API', max_length=20)),
                ('site_name', models.CharField(default='Dhivehinoos.net', max_length=255)),
                ('site_description', models.TextField(default='AI-generated fictional content for research purposes', help_text='Site description for SEO and about pages')),
                ('allow_comments', models.BooleanField(default=True, help_text='Whether to allow comments on articles')),
                ('require_comment_approval', models.BooleanField(default=True, help_text='Whether comments need admin approval before being visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
