# Generated by Django 5.2.7 on 2025-10-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_update_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='Authentic Maldivian Dhivehi Twitter thoughts and cultural insights for the Maldivian diaspora worldwide. Connect with your roots through curated Dhivehi content.', help_text='Site description for SEO and about pages'),
        ),
    ]
