# Generated by Django 5.2.7 on 2025-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_sitesettings_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_article_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', help_text='Default status for new articles created via API', max_length=20),
        ),
    ]
