# Generated by Django 5.2.7 on 2025-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_add_scheduled_status_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='emaildym@proton.me', help_text='Main contact email address for the website', max_length=254),
        ),
    ]
