# Generated by Django 5.2.7 on 2025-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_sitesettings_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='comment_webhook_enabled',
            field=models.BooleanField(default=False, help_text='Whether to send approved comments to webhook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='comment_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret key for webhook authentication (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='comment_webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL to send approved comments to (e.g., n8n workflow URL)', null=True),
        ),
    ]
