# Generated by Django 5.2.7 on 2025-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_sitesettings_comment_webhook_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='story_cards_columns',
            field=models.PositiveIntegerField(default=3, help_text='Number of columns to display story cards (1-6)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_cards_rows',
            field=models.PositiveIntegerField(default=3, help_text='Number of rows to display story cards (1-10)'),
        ),
    ]
