# Generated by Django 5.2.7 on 2025-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_sitesettings_story_cards_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_image_matching',
            field=models.BooleanField(default=True, help_text='Whether to automatically match articles with reusable images of prominent people and institutions'),
        ),
    ]
