# Generated by Django 5.2.7 on 2025-11-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_sitesettings_enable_image_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_pagination_size',
            field=models.PositiveIntegerField(default=10, help_text='Default number of articles to display per page (5-100)'),
        ),
    ]
