version: '3'

services:
  dhivehinoos_redis:
    image: redis:7-alpine
    container_name: dhivehinoos_redis
    restart: unless-stopped
    ports:
      - "8054:6379"  # Unique port for dhivehinoos redis
    volumes:
      - /opt/dhivehinoos/redis:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dhivehinoos_backend:
    image: dhimarketer/backend:latest
    container_name: dhivehinoos_backend
    restart: unless-stopped
    ports:
      - "8052:8000"  # Unique port for dhivehinoos backend
    # Load environment variables from .env file in this directory
    env_file:
      - .env
    volumes:
      - /opt/dhivehinoos/database:/app/database
      - /opt/dhivehinoos/media/articles:/app/media/articles
      - /opt/dhivehinoos/media/ads:/app/media/ads
      - /opt/dhivehinoos/static:/app/static
      - /opt/dhivehinoos/logs:/app/logs
    environment:
      # These explicit variables will override any same-named variables from .env
      - DJANGO_SETTINGS_MODULE=dhivehinoos_backend.settings
      - DEBUG=False
      - ALLOWED_HOSTS=dhivehinoos.net,www.dhivehinoos.net,localhost
      - DATABASE_URL=sqlite:////app/database/db.sqlite3
      - SECRET_KEY=${SECRET_KEY}
      - API_INGEST_KEY=${API_INGEST_KEY}
      - USE_MEMORY_CACHE=false
      - USE_TLS=true
      - REDIS_URL=redis://dhivehinoos_redis:6379/0
    depends_on:
      dhivehinoos_redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/articles/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  dhivehinoos_frontend:
    image: dhimarketer/frontend:latest
    container_name: dhivehinoos_frontend
    restart: unless-stopped
    ports:
      - "8053:80"  # Unique port for dhivehinoos frontend
    depends_on:
      dhivehinoos_backend:
        condition: service_healthy

# Removed unused 'volumes:' and 'networks:' definitions at the root level
# Using host volumes instead for better control and persistence
