# Generated by Django 5.2.7 on 2025-10-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
    ]
