# Generated by Django 5.2.7 on 2025-10-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Uploaded image file (optional)', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, help_text='External image URL (optional)', null=True),
        ),
    ]
