# Generated by Django 5.2.7 on 2025-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_publishingschedule_article_publishing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='proposed_url',
            field=models.CharField(blank=True, help_text='Custom URL path for this article (optional)', max_length=500, null=True),
        ),
    ]
