# Generated by Django 5.2.7 on 2025-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_add_image_reuse_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reusableimage',
            options={'ordering': ['entity_name'], 'verbose_name': 'Reusable Image', 'verbose_name_plural': 'Reusable Images'},
        ),
        migrations.AlterUniqueTogether(
            name='reusableimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='alternative_names',
            field=models.TextField(blank=True, help_text="Alternative names separated by commas (e.g., 'Ibu Solih, President Solih, Ibrahim Solih')"),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the image'),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='display_name',
            field=models.CharField(help_text='Auto-generated display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='entity_name',
            field=models.CharField(help_text="Identifiable name (e.g., 'President Ibrahim Mohamed Solih', 'Maldives Police Service')", max_length=255),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='entity_type',
            field=models.CharField(choices=[('politician', 'Politician'), ('institution', 'Institution'), ('organization', 'Organization'), ('public_figure', 'Public Figure'), ('other', 'Other')], default='other', help_text='Type of entity this image represents', max_length=50),
        ),
        migrations.AlterField(
            model_name='reusableimage',
            name='image_file',
            field=models.ImageField(help_text='Upload the image file', upload_to='reusable_images/'),
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='image_sequence',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='image_variant',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='name_variations',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='source',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='reusableimage',
            name='verified_by',
        ),
    ]
