# Generated by Django 5.2.7 on 2025-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_simplify_reusable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableimage',
            name='alternative_names',
            field=models.TextField(blank=True, help_text="Optional: Alternative names separated by commas (e.g., 'Ibu Solih, President Solih, Ibrahim Solih')", null=True),
        ),
    ]
