# Generated by Django 5.2.7 on 2025-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_make_alternative_names_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableimage',
            name='entity_name',
            field=models.CharField(blank=True, help_text="Optional: Identifiable name (e.g., 'President Ibrahim Mohamed Solih'). If empty, will be generated from filename.", max_length=255),
        ),
    ]
