# Generated by Django 5.2.7 on 2025-10-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_make_entity_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reuse_images',
            field=models.ManyToManyField(blank=True, help_text='Multiple reusable images that match this article content (max 4)', related_name='articles_using_image', to='articles.reusableimage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reused_image',
            field=models.ForeignKey(blank=True, help_text='Primary reusable image used for this article (for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_articles', to='articles.reusableimage'),
        ),
    ]
