# Generated by Django 5.2.7 on 2025-10-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_add_reuse_images_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fit', models.CharField(choices=[('cover', 'Cover (crop to fit)'), ('contain', 'Contain (fit within bounds)'), ('fill', 'Fill (stretch to fit)'), ('scale-down', 'Scale Down (shrink if needed)'), ('none', 'None (original size)')], default='cover', help_text='How images should fit within their containers', max_length=20)),
                ('image_position', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='top', help_text='Which part of the image should be visible when cropped', max_length=20)),
                ('image_orientation', models.CharField(choices=[('auto', 'Auto-detect'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], default='auto', help_text='Force specific orientation for all images', max_length=20)),
                ('main_image_height', models.PositiveIntegerField(default=400, help_text='Height in pixels for main article images')),
                ('reuse_image_height', models.PositiveIntegerField(default=300, help_text='Height in pixels for reuse images')),
                ('thumbnail_height', models.PositiveIntegerField(default=150, help_text='Height in pixels for thumbnail images')),
                ('main_image_aspect_ratio', models.CharField(default='16:9', help_text='Aspect ratio for main images (e.g., 16:9, 4:3, 1:1)', max_length=10)),
                ('reuse_image_aspect_ratio', models.CharField(default='4:3', help_text='Aspect ratio for reuse images (e.g., 16:9, 4:3, 1:1)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these settings are currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Display Settings',
                'verbose_name_plural': 'Image Display Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
