# Generated by Django 5.2.7 on 2025-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_imagedisplaysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='custom_main_height',
            field=models.PositiveIntegerField(default=9, help_text='Custom height for main image aspect ratio'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='custom_main_width',
            field=models.PositiveIntegerField(default=16, help_text='Custom width for main image aspect ratio'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='custom_reuse_height',
            field=models.PositiveIntegerField(default=3, help_text='Custom height for reuse image aspect ratio'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='custom_reuse_width',
            field=models.PositiveIntegerField(default=4, help_text='Custom width for reuse image aspect ratio'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this settings configuration'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='desktop_image_height',
            field=models.PositiveIntegerField(default=400, help_text='Height in pixels for desktop devices'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='enable_lazy_loading',
            field=models.BooleanField(default=True, help_text='Enable lazy loading for better performance'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='enable_webp_conversion',
            field=models.BooleanField(default=True, help_text='Convert images to WebP format for better compression'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='image_border_radius',
            field=models.PositiveIntegerField(default=8, help_text='Border radius in pixels for rounded corners'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='image_hover_effect',
            field=models.BooleanField(default=True, help_text='Add hover effects to images'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='image_quality',
            field=models.CharField(choices=[('high', 'High Quality'), ('medium', 'Medium Quality'), ('low', 'Low Quality (Fast Loading)')], default='medium', help_text='Image quality vs loading speed trade-off', max_length=10),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='image_shadow',
            field=models.BooleanField(default=True, help_text='Add shadow effect to images'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='mobile_image_height',
            field=models.PositiveIntegerField(default=250, help_text='Height in pixels for mobile devices'),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='settings_name',
            field=models.CharField(default='Default Image Settings', help_text='Name for this settings configuration', max_length=100),
        ),
        migrations.AddField(
            model_name='imagedisplaysettings',
            name='tablet_image_height',
            field=models.PositiveIntegerField(default=350, help_text='Height in pixels for tablet devices'),
        ),
        migrations.AlterField(
            model_name='imagedisplaysettings',
            name='main_image_aspect_ratio',
            field=models.CharField(choices=[('16:9', '16:9 (Widescreen)'), ('4:3', '4:3 (Standard)'), ('3:2', '3:2 (Classic)'), ('1:1', '1:1 (Square)'), ('21:9', '21:9 (Ultrawide)'), ('9:16', '9:16 (Portrait)'), ('custom', 'Custom')], default='16:9', help_text='Aspect ratio for main images (e.g., 16:9, 4:3, 1:1)', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagedisplaysettings',
            name='reuse_image_aspect_ratio',
            field=models.CharField(choices=[('16:9', '16:9 (Widescreen)'), ('4:3', '4:3 (Standard)'), ('3:2', '3:2 (Classic)'), ('1:1', '1:1 (Square)'), ('21:9', '21:9 (Ultrawide)'), ('9:16', '9:16 (Portrait)'), ('custom', 'Custom')], default='4:3', help_text='Aspect ratio for reuse images (e.g., 16:9, 4:3, 1:1)', max_length=10),
        ),
    ]
