# Generated by Django 5.2.7 on 2025-10-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_imagedisplaysettings_custom_main_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageDisplaySettings',
            new_name='ImageSettings',
        ),
    ]
