# Generated by Django 5.2.7 on 2025-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_imagedisplaysettings_to_imagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_fragments',
            field=models.TextField(blank=True, help_text='Source fragments providing context for the story (will be displayed in italics)', null=True),
        ),
    ]
