# Generated by Django 5.2.7 on 2025-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_add_article_indexes'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['article', 'ip_address'], name='vote_article_ip_idx'),
        ),
    ]
