# Generated by Django 5.2.7 on 2025-10-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(help_text='External image URL'),
        ),
    ]
