# Generated by Django 5.2.7 on 2025-10-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='destination_url',
            field=models.URLField(blank=True, help_text='Optional target link', null=True),
        ),
    ]
