# Generated by Django 5.2.7 on 2025-10-03 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_destination_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When the ad should stop showing (optional)', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the ad should start showing'),
        ),
    ]
