# Generated by Django 5.2.7 on 2025-10-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_end_date_ad_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(blank=True, help_text='External image URL (optional)', null=True),
        ),
    ]
