# Generated by Django 5.2.7 on 2025-10-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Uploaded image file (optional)', null=True, upload_to='ads/'),
        ),
    ]
