# Generated by Django 5.2.7 on 2025-10-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('top_banner', 'Top Banner'), ('sidebar', 'Sidebar'), ('between_articles', 'Between Articles'), ('bottom_banner', 'Bottom Banner'), ('article_header', 'Article Header'), ('article_footer', 'Article Footer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of where this placement appears')),
                ('is_active', models.BooleanField(default=True)),
                ('max_ads', models.PositiveIntegerField(default=1, help_text='Maximum number of ads that can be shown in this placement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='Where this ad should be displayed', null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.adplacement'),
        ),
    ]
