# Generated by Django 5.2.7 on 2025-10-03 03:06

from django.db import migrations


def create_default_placements(apps, schema_editor):
    """Create default ad placements"""
    AdPlacement = apps.get_model('ads', 'AdPlacement')
    
    placements = [
        ('top_banner', 'Top Banner', 'Banner ad displayed at the top of the page', 1),
        ('sidebar', 'Sidebar', 'Ad displayed in the sidebar', 2),
        ('between_articles', 'Between Articles', 'Ad displayed between article listings', 1),
        ('bottom_banner', 'Bottom Banner', 'Banner ad displayed at the bottom of the page', 1),
        ('article_header', 'Article Header', 'Ad displayed at the top of individual articles', 1),
        ('article_footer', 'Article Footer', 'Ad displayed at the bottom of individual articles', 1),
    ]
    
    for name, display_name, description, max_ads in placements:
        AdPlacement.objects.get_or_create(
            name=name,
            defaults={
                'description': description,
                'max_ads': max_ads,
                'is_active': True
            }
        )


def assign_existing_ads_to_default_placement(apps, schema_editor):
    """Assign existing ads to the top_banner placement"""
    Ad = apps.get_model('ads', 'Ad')
    AdPlacement = apps.get_model('ads', 'AdPlacement')
    
    # Get or create the top_banner placement
    placement, created = AdPlacement.objects.get_or_create(
        name='top_banner',
        defaults={
            'description': 'Banner ad displayed at the top of the page',
            'max_ads': 1,
            'is_active': True
        }
    )
    
    # Assign all existing ads to this placement
    Ad.objects.filter(placement__isnull=True).update(placement=placement)


def reverse_assignments(apps, schema_editor):
    """Reverse the assignment of ads to placements"""
    Ad = apps.get_model('ads', 'Ad')
    Ad.objects.all().update(placement=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adplacement_ad_placement'),
    ]

    operations = [
        migrations.RunPython(create_default_placements, migrations.RunPython.noop),
        migrations.RunPython(assign_existing_ads_to_default_placement, reverse_assignments),
    ]
